<?php

declare (strict_types=1);
namespace SVG;

use SVG\Fonts\Font_Registry;
use SVG\Nodes\Structures\Svg_Document_Fragment;
use SVG\Rasterization\Svg_Rasterizer;
use SVG\Reading\Svg_Reader;
use SVG\Writing\Svg_Writer;
/**
 * This is the main class for any SVG image, as it hosts the document root and
 * offers conversion methods.
 */
class SVG
{
    /**
     * @var SVGReader $reader The singleton reader used by this class.
     */
    private static ?\SVG\Reading\Svg_Reader $reader = null;
    private static ?\SVG\Fonts\Font_Registry $font_registry = null;
    /**
     * @var SVGDocumentFragment $document This image's root `svg` node/tag.
     */
    private Svg_Document_Fragment $document;
    /**
     * @param mixed $width    The image's width (any CSS length).
     * @param mixed $height   The image's height (any CSS length).
     */
    public function __construct($width = null, $height = null)
    {
        $this->document = new Svg_Document_Fragment($width, $height);
    }
    /**
     * @return SVGDocumentFragment The document/root node of this image.
     */
    public function get_document(): Svg_Document_Fragment
    {
        return $this->document;
    }
    /**
     * Converts this image into a rasterized GD resource of the given size.
     *
     * The resulting image resource supports transparency and represents the
     * SVG as accurately as possible (with PHP's limited imaging functions).
     * Note that, since images in SVG have an innate size, the given size only
     * scales the output canvas and does not influence element positions.
     *
     * @param int $width              The target canvas's width, in pixels.
     * @param int $height             The target canvas's height, in pixels.
     * @param string|null $background The background color (hex/rgb[a]/hsl[a]/...).
     *
     * @return resource The rasterized image as a GD resource (with alpha).
     */
    public function to_raster_image(int $width, int $height, ?string $background = null)
    {
        $doc_width = $this->document->get_width();
        $doc_height = $this->document->get_height();
        $view_box = $this->document->get_view_box();
        $rasterizer = new Svg_Rasterizer($doc_width, $doc_height, $view_box, $width, $height, $background);
        $rasterizer->set_font_registry(self::get_font_registry());
        $this->document->rasterize($rasterizer);
        return $rasterizer->finish();
    }
    /**
     * @see SVG::toXMLString() For the implementation (this is a wrapper).
     */
    public function __toString(): string
    {
        return $this->to_xml_string();
    }
    /**
     * Converts this image's document tree into an XML source code string.
     *
     * Note that an image parsed from an XML string might not have the exact
     * same XML string generated by this method, since the output is optimized
     * and formatted according to specific rules.
     *
     * @param bool $standalone optional, false omits the leading <?xml tag
     *
     * @return string This image's document tree as an XML string.
     */
    public function to_xml_string(bool $standalone = true): string
    {
        $writer = new Svg_Writer($standalone);
        $writer->write_node($this->document);
        return $writer->get_string();
    }
    /**
     * Parses the given XML string into an instance of this class.
     *
     * @param string $string The XML string to parse.
     *
     * @return SVG A new image, with the nodes parsed from the XML.
     */
    public static function from_string(string $string): ?SVG
    {
        return self::get_reader()->parse_string($string);
    }
    /**
     * Reads the file at the given path as an XML string, and then parses it
     * into an instance of this class.
     *
     * @param string $file The path to the file to parse.
     *
     * @return SVG A new image, with the nodes parsed from the XML.
     */
    public static function from_file(string $file): ?SVG
    {
        return self::get_reader()->parse_file($file);
    }
    /**
     * @return SVGReader The singleton reader shared across all instances.
     */
    private static function get_reader(): Svg_Reader
    {
        if (!isset(self::$reader)) {
            self::$reader = new Svg_Reader();
        }
        return self::$reader;
    }
    /**
     * @return FontRegistry The singleton font registry.
     */
    private static function get_font_registry(): Font_Registry
    {
        if (!isset(self::$font_registry)) {
            self::$font_registry = new Font_Registry();
        }
        return self::$font_registry;
    }
    /**
     * Register a font file to be used when rasterizing text.
     *
     * @param string $path The path to the font file.
     */
    public static function add_font(string $path): void
    {
        self::get_font_registry()->add_font($path);
    }
}